packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  '@google/genai': true
  cpu-features: true
  electron: true
  electron-winstaller: true
  esbuild: true
  protobufjs: true
  sqlite3: true
  ssh2: true
