import fs from "node:fs";
import path from "node:path";
import crypto from "node:crypto";
import { fileURLToPath } from "node:url";

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const envPath = path.join(repoRoot, ".env");
const outputPath = path.join(repoRoot, "apps", "desktop", "packagedEnv.generated.ts");

const allowList = [
  "DARTSNUT_MODEL_DECRYPTION_KEY",
  "DARTSNUT_BASE_API",
  "DARTSNUT_SUPABASE_URL",
  "DARTSNUT_SUPABASE_ANON_KEY",
  "DARTSNUT_SUPABASE_DEVICE_TABLE",
  "DARTSNUT_GOOGLE_CLIENT_ID"
];

const parsed = fs.existsSync(envPath)
  ? parseEnvFile(fs.readFileSync(envPath, "utf-8"))
  : {};

function parseEnvFile(source) {
  const parsedEnv = {};
  for (const rawLine of source.split(/\r?\n/)) {
    const line = rawLine.trim();
    if (!line || line.startsWith("#")) {
      continue;
    }
    const equalsAt = line.indexOf("=");
    if (equalsAt <= 0) {
      continue;
    }
    const key = line.slice(0, equalsAt).trim();
    let value = line.slice(equalsAt + 1).trim();
    if (
      (value.startsWith("\"") && value.endsWith("\"")) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }
    parsedEnv[key] = value;
  }
  return parsedEnv;
}

const env = {};
for (const key of allowList) {
  const value = process.env[key] ?? parsed[key];
  if (typeof value === "string" && value.trim()) {
    env[key] = value.trim();
  }
}

function encodeValue(value) {
  const bytes = Buffer.from(value, "utf-8");
  const seed = crypto.randomBytes(1)[0] || 97;
  const encoded = Array.from(bytes, (byte, index) => byte ^ ((seed + index * 31) & 0xff));
  return { seed, encoded };
}

const encodedEnv = Object.fromEntries(
  Object.entries(env).map(([key, value]) => [key, encodeValue(value)])
);

const lines = [
  "/* Auto-generated by scripts/generate_packaged_env.mjs. Do not edit by hand. */",
  "const ENCODED_ENV: Record<string, { seed: number; encoded: number[] }> =",
  `${JSON.stringify(encodedEnv, null, 2)};`,
  "",
  "function decodePackagedValue(seed: number, encoded: number[]): string {",
  "  const bytes = encoded.map((byte, index) => byte ^ ((seed + index * 31) & 0xff));",
  "  return Buffer.from(bytes).toString(\"utf-8\");",
  "}",
  "",
  "export const PACKAGED_ENV: Record<string, string> = Object.fromEntries(",
  "  Object.entries(ENCODED_ENV).map(([key, value]) => [key, decodePackagedValue(value.seed, value.encoded)])",
  ");",
  ""
];

fs.writeFileSync(outputPath, lines.join("\n"));
console.log(`[packaged-env] generated ${path.relative(repoRoot, outputPath)} with ${Object.keys(env).length} keys`);
