title: "Dartsnut Emulator"
description: "Desktop emulator for Dartsnut widgets and games."
remote_theme: just-the-docs/just-the-docs

markdown: kramdown

# Plugins (GitHub Pages supports these)
plugins:
  - jekyll-remote-theme

# Optional: repo link in header
aux_links:
  "Repository":
    - "https://github.com/Dartsnut/dartsnut_emulator"
